package ru.itis.oris.test.playground.model;

import com.slavikjunior.deorm.annotations.Column;
import com.slavikjunior.deorm.annotations.Id;
import com.slavikjunior.deorm.annotations.Table;
import com.slavikjunior.deorm.orm.Entity;

import java.sql.Timestamp;
import java.sql.Types;
import java.util.Objects;

@Table(name = "posts")
public class Post implements Entity {

    @Id(autogenerated = true)
    @Column(name = "id", nullable = false, type = Types.INTEGER)
    private int id;
    @Column(name = "title", nullable = false, type = Types.VARCHAR)
    private String title;
    @Column(name = "author_id", nullable = false, type = Types.INTEGER)
    private int authorId;
    @Column(name = "content", nullable = false, type = Types.VARCHAR)
    private String content;
    @Column(name = "created_date", nullable = false, type = Types.TIMESTAMP)
    private Timestamp createdDate = new Timestamp(System.currentTimeMillis());

    public Post(int id, String title, int authorId, String content, Timestamp createdDate) {
        this.id = id;
        this.title = title;
        this.authorId = authorId;
        this.content = content;
        this.createdDate = createdDate;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getAuthorId() {
        return authorId;
    }

    public void setAuthorId(int authorId) {
        this.authorId = authorId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Timestamp getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Post post = (Post) o;
        return id == post.id && authorId == post.authorId && Objects.equals(title, post.title) && Objects.equals(content, post.content) && Objects.equals(createdDate, post.createdDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, title, authorId, content, createdDate);
    }

    @Override
    public String toString() {
        return "Post{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", authorId=" + authorId +
                ", content='" + content + '\'' +
                ", createdDate=" + createdDate +
                '}';
    }
}
