package ru.itis.oris.test.model;

import com.slavikjunior.deorm.annotations.Column;
import com.slavikjunior.deorm.annotations.Id;
import com.slavikjunior.deorm.annotations.Table;
import com.slavikjunior.deorm.orm.Entity;

import java.sql.Timestamp;
import java.sql.Types;
import java.util.Objects;

@Table(name = "comments")
public class Comment implements Entity {
    @Id(autogenerated = true)
    @Column(name = "id", nullable = false, type = Types.INTEGER)
    private int id;

    @Column(name = "post_id", nullable = false, type = Types.INTEGER)
    private int postId;

    @Column(name = "user_id", nullable = false, type = Types.INTEGER)
    private int userId;

    @Column(name = "content", nullable = false, type = Types.VARCHAR)
    private String content;

    @Column(name = "created_date", nullable = false, type = Types.TIMESTAMP)
    private Timestamp createdDate = new Timestamp(System.currentTimeMillis());

    public Comment(int id, int postId, int userId, String content, Timestamp createdDate) {
        this.id = id;
        this.postId = postId;
        this.userId = userId;
        this.content = content;
        this.createdDate = createdDate;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getPostId() {
        return postId;
    }

    public void setPostId(int postId) {
        this.postId = postId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Timestamp getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Comment comment = (Comment) o;
        return id == comment.id && postId == comment.postId && userId == comment.userId && Objects.equals(content, comment.content) && Objects.equals(createdDate, comment.createdDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, postId, userId, content, createdDate);
    }

    @Override
    public String toString() {
        return "Comment{" +
                "id=" + id +
                ", postId=" + postId +
                ", userId=" + userId +
                ", content='" + content + '\'' +
                ", createdDate=" + createdDate +
                '}';
    }
}