package ru.itis.oris.test.model;

import com.slavikjunior.deorm.annotations.Column;
import com.slavikjunior.deorm.annotations.Id;
import com.slavikjunior.deorm.annotations.Table;

import java.sql.Types;
import java.util.Objects;

@Table(name = "users")
public class User {

    @Id(autogenerated = true)
    @Column(name = "id", nullable = false, type = Types.INTEGER)
    private int id;
    @Column(name = "user_name", nullable = false, type = Types.VARCHAR)
    private String userName;
    @Column(name = "hashed_password", nullable = false, type = Types.VARCHAR)
    private String hashedPassword;
    @Column(name = "role", nullable = false, type = Types.VARCHAR)
    private Role role;

    public User(int id, String userName, String hashedPassword, Role role) {
        this.id = id;
        this.userName = userName;
        this.hashedPassword = hashedPassword;
        this.role = role;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getHashedPassword() {
        return hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id && Objects.equals(userName, user.userName) && Objects.equals(hashedPassword, user.hashedPassword) && role == user.role;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userName, hashedPassword, role);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", hashedPassword='" + hashedPassword + '\'' +
                ", role=" + role +
                '}';
    }
}
